### STAGE 1: Build ###
FROM node:12.7-alpine AS build
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build --env=prod


### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY dev/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/angular-car365-front /usr/share/nginx/html

